### ISSUE TITLE
New lit support

### ISSUE THREAD

**Issue by GHNewbiee** [open-wc/lit-demos#7]
Hi, are you planning to provide or update the demos so as they comply with new **lit**? *Tia*

**Comment by Westbrook** [comment]
@thepassle are these the demos that publish straight to WebComponents.dev? In which case maybe we want both? If not, then I’d be quite happy to accept a PR with this update @GHNewbiee!

**Comment by thepassle** [comment]
We once planned to sync the demos to wc.dev, but I think we never got round to them (or at least: there's some difference between the demos in this repo, and the actual demos in wc.dev), so I guess this repo is stale. I've updated the demos on wc.dev to use the new version of `lit`.
